name: CI Pipeline

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:     

jobs:
  # Job for linting, type checking, unit testing
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
        
      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies and iOS Pods
      - name: Install dependencies
        run: npm i --legacy-peer-deps

      # # Step 4: Run linters (ESLint)
      # - name: Run ESLint
      #   run: npm lint

      # # Step 6: Run unit tests (Jest)
      # - name: Run unit tests
      #   run: yarn test --coverage

  # Job for Android build
  build-android:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm i --legacy-peer-deps
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build Android
        run: npm build:android

  # Job for iOS build
  build-ios:
    runs-on: macos-latest  # macOS runner required for iOS builds
    needs: build-and-test
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm i --legacy-peer-deps

      - name: Build iOS
        run: npm ios:build
